### ISSUE TITLE
installation error - Creating bcinab_gui_1

### ISSUE THREAD

**Issue by MikeGlue** [tfenster/BCinaB#15]
Get the following error when trying to do the installation. Have tried reverting to stable Docker (via uninstall & install) as I was initially using a nightly build but same error happens. Running Windows 10 1809.

![annotation 2019-01-04 211607](https://user-images.githubusercontent.com/5204734/50719493-bcb3f980-106a-11e9-9306-5add802ec314.jpg)

![annotation 2019-01-04 215127](https://user-images.githubusercontent.com/5204734/50719501-e9681100-106a-11e9-8cb6-285277fe19b4.jpg)

**Comment by tfenster** [comment]
Is anything running on port 8080? That would give the same error. Could you try to open docker-compose.yml with a text editor, find "8080" and change it to e.g. "8181" and then try again?

**Comment by MikeGlue** [comment]
Oops yeah bonehead move on my part there. Changed port to 8082 but now get this error. 

![annotation 2019-01-06 003258](https://user-images.githubusercontent.com/5204734/50732550-4e933380-114b-11e9-9a5d-4a60cecc4265.jpg)

**Comment by tfenster** [comment]
Strange, that error would usually indicate that the gui container can't reach the api container but as your screenshot shows, the api conatiner is up and running. How long does the api container take to start?

**Comment by MikeGlue** [comment]
Well I tried it on another machine (my main one actually) and it works just fine. The initial machine I was trying it on should've also worked but I'll do some more investigation to see why it doesn't. I'll close this for now and reopen if I find anything useful, but until then I'm good to go on my main machine!
