### ISSUE TITLE
Support for navcontainerhelper

### ISSUE THREAD

**Issue by ajkauffmann** [tfenster/BCinaB#16]
Suggestion to support navcontainerhelper by creating these two volumes (bcsandbox being the name of the container):

![image](https://user-images.githubusercontent.com/19155831/50726017-37caed80-1107-11e9-83d3-feb4b41798fa.png)

It's not enough to just create the volumes, you need to create the folder for the container. The only way (I guess) is to get this working is by creating a volume in bcinab-api container to C:\ProgramData\navcontainerhelper on the host.

**Comment by tfenster** [comment]
@ajkauffmann I think I'll implement this as a checkbox "enable navcontainerhelper volumes" or something like that in the create-wizard. Makes sense for you? The c:\navpfiles share is not necessary?

**Comment by ajkauffmann** [comment]
That's what I was thinking of.

The navpfiles share is used when you include CSide. Not needed for now, you need to add some other stuff to AdditionalSetup.ps1 for that. I would look at that later, not now.

**Comment by tfenster** [comment]
Ok, if you now mount c:\programdata\navcontainerhelper to the same folder in the api container, then the create wizard will show a "navcontainerhelper volumes" checkbox. If you select that, the mentioned folders are created and added as binds to a new container. 

Will also be available with alpha6
