### ISSUE TITLE
Support to update hosts file

### ISSUE THREAD

**Issue by ajkauffmann** [tfenster/BCinaB#17]
Suggestion to update hosts file the same way as navcontainerhelper does. Reason for asking is the network issue on Windows 1809 resulting in new ip-address for the containers after each reboot. The updatehosts option from navcontainerhelper resolves this.

Steps needed:

Create a volume to c:\windows\system32\drivers\etc

![image](https://user-images.githubusercontent.com/19155831/50726070-0acb0a80-1108-11e9-8572-7ea323d3db1a.png)

Copy updatehosts.ps1 to the my folder
File could be downloaded from https://raw.githubusercontent.com/Microsoft/navcontainerhelper/master/ContainerHandling/updatehosts.ps1 (and let's hope Freddy doesn't change that location)

Add a line to AdditionalOutput.ps1 to run updatehosts: 
. (Join-Path $PSScriptRoot "updatehosts.ps1") -hostsFile "c:\driversetc\hosts" -hostname bcsandbox -ipAddress $ip

Only possible when you support navcontainerhelper as requested in the other issue.

**Comment by tfenster** [comment]
@ajkauffmann I've implemented a more generic solution that not only works with NAV/BC containers and also is better at cleaning up (I hope ;) ). Give it a try when alpha6 is released and let me know if you like it
