### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by AndriusAndrulevicius** [tfenster/BCinaB#19]
When trying to install the tool I'm getting the following error(s):
docker-compose : Pulling api (arssolvendi.azurecr.io/bcinab-api:alpha6)...
At line:1 char:1
+ docker-compose -p bcinab -f c:\programdata\bcinab\docker-compose.yml  ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (Pulling api (ar...-api:alpha6)...:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
alpha6: Pulling from bcinab-api
Pulling gui (arssolvendi.azurecr.io/bcinab-gui:alpha6)...
alpha6: Pulling from bcinab-gui
Recreating bcinab_api_1 ... 
[1A[2KRecreating bcinab_api_1 ... [32mdone[0m[1B
Recreating bcinab_gui_1 ... 
[1A[2KRecreating bcinab_gui_1 ... [31merror[0m[1B
ERROR: for bcinab_gui_1  Cannot start service gui: failed to create endpoint bcinab_gui_1 on network bcinab_backend: hnsCall failed in Win32: The process cannot access the file because it is 
being used by another process. (0x20)
ERROR: for gui  Cannot start service gui: failed to create endpoint bcinab_gui_1 on network bcinab_backend: hnsCall failed in Win32: The process cannot access the file because it is being 
used by another process. (0x20)
Encountered errors while bringing up the project.

Not even sure how to start resolving this...

**Comment by tfenster** [comment]
Looks like you have something else running on port 8080. Might that be possible?

**Comment by demiliani** [comment]
Same error to me just now, but despite that all is installed:
![bcinab_alpha6](https://user-images.githubusercontent.com/33155438/50792254-9b4e4a00-12c4-11e9-88fd-0d3a23539639.jpg)

**Comment by Hansdevries** [comment]
Hi

Having the same issue. Blanc server 2019!

**Comment by tfenster** [comment]
@demiliani you actually don't seem to have an error, only weird formatting. Are you running in ISE or standalone PowerShell?

@Hansdevries what is your exact output?

**Comment by demiliani** [comment]
@tfenster running on ISE with 
Set-ExecutionPolicy -Scope Process -ExecutionPolicy Bypass 
in order to bypass errors on non signed scripts. It works :)

**Comment by demiliani** [comment]
Just a question: for future updates, we only need to re-run Start-BCinaB in PS isn't it?

**Comment by tfenster** [comment]
@demiliani could you try in a regular PowerShell (no ISE) and see if it looks better? Updates are done with 
```
Stop-BCinaB
Update-BCinaB
Start-BCinaB
```

**Comment by Hansdevries** [comment]
tried it again:
Creating bcinab_api_1 ... done
Creating bcinab_gui_1 ... done
Attaching to bcinab_api_1, bcinab_gui_1
api_1  |
api_1  | Unhandled Exception:
api_1  | Unhandled Exception: System.TimeoutException: The operation has timed out.
api_1  |    at System.IO.Pipes.NamedPipeClientStream.ConnectInternal(Int32 timeout, CancellationToken cancellationToken, Int32 startTime)
api_1  |    at System.IO.Pipes.NamedPipeClientStream.<>c__DisplayClass20_0.<ConnectAsync>b__0()
api_1  |    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
api_1  | --- End of stack trace from previous location where exception was thrown ---
api_1  |    at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
api_1  | --- End of stack trace from previous location where exception was thrown ---
api_1  |    at Docker.DotNet.DockerClient.<>c__DisplayClass6_0.<<-ctor>b__0>d.MoveNext()
api_1  | --- End of stack trace from previous location where exception was thrown ---
api_1  |    at Microsoft.Net.Http.Client.ManagedHandler.ProcessRequestAsync(HttpRequestMessage request, CancellationToken cancellationToken)
api_1  |    at Microsoft.Net.Http.Client.ManagedHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
api_1  |    at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
api_1  |    at Docker.DotNet.DockerClient.PrivateMakeRequestAsync(TimeSpan timeout, HttpCompletionOption completionOption, HttpMethod method, String path, IQueryString queryString, IDictionary`2 headers, IRequestContent data, CancellationToken cancellationToken)
api_1  |    at Docker.DotNet.DockerClient.MakeRequestForStreamAsync(IEnumerable`1 errorHandlers, HttpMethod method, String path, IQueryString queryString, IRequestContent body, IDictionary`2 headers, TimeSpan timeout, CancellationToken token)
api_1  |    at Docker.DotNet.Models.StreamUtil.MonitorStreamForMessagesAsync[T](Task`1 streamTask, DockerClient client, CancellationToken cancel, IProgress`1 progress)
api_1  |    at api.Services.EngineMonitorService.ListenToEngine() in C:\src\api\Services\EngineMonitorService.cs:line 54
api_1  |    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
api_1  | --- End of stack trace from previous location where exception was thrown ---
api_1  |    at System.Threading.ThreadPoolWorkQueue.Dispatch()
api_1  | System.TimeoutException: The operation has timed out.
api_1  |    at System.IO.Pipes.NamedPipeClientStream.ConnectInternal(Int32 timeout, CancellationToken cancellationToken, Int32 startTime)
api_1  |    at System.IO.Pipes.NamedPipeClientStream.<>c__DisplayClass20_0.<ConnectAsync>b__0()
api_1  |    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
api_1  | --- End of stack trace from previous location where exception was thrown ---
api_1  |    at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
api_1  | --- End of stack trace from previous location where exception was thrown ---
api_1  |    at Docker.DotNet.DockerClient.<>c__DisplayClass6_0.<<-ctor>b__0>d.MoveNext()
api_1  | --- End of stack trace from previous location where exception was thrown ---
api_1  |    at Microsoft.Net.Http.Client.ManagedHandler.ProcessRequestAsync(HttpRequestMessage request, CancellationToken cancellationToken)
api_1  |    at Microsoft.Net.Http.Client.ManagedHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
api_1  |    at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
api_1  |    at Docker.DotNet.DockerClient.PrivateMakeRequestAsync(TimeSpan timeout, HttpCompletionOption completionOption, HttpMethod method, String path, IQueryString queryString, IDictionary`2 headers, IRequestContent data, CancellationToken cancellationToken)
api_1  |    at Docker.DotNet.DockerClient.MakeRequestForStreamAsync(IEnumerable`1 errorHandlers, HttpMethod method, String path, IQueryString queryString, IRequestContent body, IDictionary`2 headers, TimeSpan timeout, CancellationToken token)
api_1  |    at Docker.DotNet.Models.StreamUtil.MonitorStreamForMessagesAsync[T](Task`1 streamTask, DockerClient client, CancellationToken cancel, IProgress`1 progress)
api_1  |    at api.Services.EngineMonitorService.ListenToEngine() in C:\src\api\Services\EngineMonitorService.cs:line 54
api_1  |    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
api_1  | --- End of stack trace from previous location where exception was thrown ---
api_1  |    at System.Threading.ThreadPoolWorkQueue.Dispatch()
api_1  | Hosting environment: Production
api_1  | Content root path: C:\app
api_1  | Now listening on: http://[::]:80
api_1  | Application started. Press Ctrl+C to shut down.
bcinab_api_1 exited with code 3762504530


webpage shows now only loading, 

![bcinab](https://user-images.githubusercontent.com/23739900/50815708-61aa2d00-131e-11e9-9deb-0c1e9a54f5df.png)

**Comment by Hansdevries** [comment]
my fault 👎  was missing the -dockerenterpriseedition startup.
no errors know:
PS C:\Users\Administrator> Start-BCinaB -DockerEnterpriseEdition
Recreating bcinab_api_1 ... done
Recreating bcinab_gui_1 ... done
Attaching to bcinab_api_1, bcinab_gui_1
api_1  | Hosting environment: Production
api_1  | Content root path: C:\app
api_1  | Now listening on: http://[::]:80
api_1  | Application started. Press Ctrl+C to shut down.

**Comment by tfenster** [comment]
@Hansdevries well, actually my fault because that should just be detected and automatically set... Will do that before beta

@AndriusAndrulevicius have you been able to get it up and running as well?

**Comment by tfenster** [comment]
@Hansdevries I've improved the PS script so that it now automatically recognizes the pipe (and whether navcontainerhelper is installed). Could you download it from here https://raw.githubusercontent.com/tfenster/BCinaB/master/stuff/BCinaB.psm1 again, import it and then just do Start-BCinaB without any parameters? That should now work

**Comment by Hansdevries** [comment]
hi, thanks, 

tried it:
updated the script: then

Start-BCinaB
Creating network "bcinab_backend" with driver "nat"
Creating network "bcinab_frontend" with driver "nat"
Creating bcinab_api_1 ... done
Creating bcinab_gui_1 ... done
Attaching to bcinab_api_1, bcinab_gui_1
api_1  |
api_1  |
api_1  | Unhandled Exception: Unhandled Exception: System.TimeoutException: The operation has timed out.
api_1  |    at System.IO.Pipes.NamedPipeClientStream.ConnectInternal(Int32 timeout, CancellationToken cancellationToken, Int32 startTime)
api_1  |    at System.IO.Pipes.NamedPipeClientStream.<>c__DisplayClass20_0.<ConnectAsync>b__0()
api_1  |    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
api_1  | --- End of stack trace from previous location where exception was thrown ---
api_1  |    at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
api_1  | --- End of stack trace from previous location where exception was thrown ---
api_1  |    at Docker.DotNet.DockerClient.<>c__DisplayClass6_0.<<-ctor>b__0>d.MoveNext()
api_1  | --- End of stack trace from previous location where exception was thrown ---
api_1  |    at Microsoft.Net.Http.Client.ManagedHandler.ProcessRequestAsync(HttpRequestMessage request, CancellationToken cancellationToken)
api_1  |    at Microsoft.Net.Http.Client.ManagedHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
api_1  |    at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
api_1  |    at Docker.DotNet.DockerClient.PrivateMakeRequestAsync(TimeSpan timeout, HttpCompletionOption completionOption, HttpMethod method, String path, IQueryString queryString, IDictionary`2 headers, IRequestContent data, CancellationToken cancellationToken)
api_1  |    at Docker.DotNet.DockerClient.MakeRequestForStreamAsync(IEnumerable`1 errorHandlers, HttpMethod method, String path, IQueryString queryString, IRequestContent body, IDictionary`2 headers, TimeSpan timeout, CancellationToken token)
api_1  |    at Docker.DotNet.Models.StreamUtil.MonitorStreamForMessagesAsync[T](Task`1 streamTask, DockerClient client, CancellationToken cancel, IProgress`1 progress)
api_1  |    at api.Services.EngineMonitorService.ListenToEngine() in C:\src\api\Services\EngineMonitorService.cs:line 54
api_1  |    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
api_1  | --- End of stack trace from previous location where exception was thrown ---
api_1  |    at System.Threading.ThreadPoolWorkQueue.Dispatch()
api_1  | System.TimeoutException: The operation has timed out.
api_1  |    at System.IO.Pipes.NamedPipeClientStream.ConnectInternal(Int32 timeout, CancellationToken cancellationToken, Int32 startTime)
api_1  |    at System.IO.Pipes.NamedPipeClientStream.<>c__DisplayClass20_0.<ConnectAsync>b__0()
api_1  |    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
api_1  | --- End of stack trace from previous location where exception was thrown ---
api_1  |    at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
api_1  | --- End of stack trace from previous location where exception was thrown ---
api_1  |    at Docker.DotNet.DockerClient.<>c__DisplayClass6_0.<<-ctor>b__0>d.MoveNext()
api_1  | --- End of stack trace from previous location where exception was thrown ---
api_1  |    at Microsoft.Net.Http.Client.ManagedHandler.ProcessRequestAsync(HttpRequestMessage request, CancellationToken cancellationToken)
api_1  |    at Microsoft.Net.Http.Client.ManagedHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
api_1  |    at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
api_1  |    at Docker.DotNet.DockerClient.PrivateMakeRequestAsync(TimeSpan timeout, HttpCompletionOption completionOption, HttpMethod method, String path, IQueryString queryString, IDictionary`2 headers, IRequestContent data, CancellationToken cancellationToken)
api_1  |    at Docker.DotNet.DockerClient.MakeRequestForStreamAsync(IEnumerable`1 errorHandlers, HttpMethod method, String path, IQueryString queryString, IRequestContent body, IDictionary`2 headers, TimeSpan timeout, CancellationToken token)
api_1  |    at Docker.DotNet.Models.StreamUtil.MonitorStreamForMessagesAsync[T](Task`1 streamTask, DockerClient client, CancellationToken cancel, IProgress`1 progress)
api_1  |    at api.Services.EngineMonitorService.ListenToEngine() in C:\src\api\Services\EngineMonitorService.cs:line 54
api_1  |    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
api_1  | --- End of stack trace from previous location where exception was thrown ---
api_1  |    at System.Threading.ThreadPoolWorkQueue.Dispatch()
bcinab_api_1 exited with code 3762504530
Gracefully stopping... (press Ctrl+C again to force)
Stopping bcinab_gui_1 ... done
PS C:\BCinaB> Start-BCinaB -DockerEnterpriseEdition
Recreating bcinab_api_1 ... done
Recreating bcinab_gui_1 ... done
Attaching to bcinab_api_1, bcinab_gui_1
api_1  | Hosting environment: Production
api_1  | Content root path: C:\app
api_1  | Now listening on: http://[::]:80
api_1  | Application started. Press Ctrl+C to shut down.


has it something to do with my local installation/settings?

**Comment by tfenster** [comment]
did you have your powershell open since running it for the first time? Because the new script actually doesn't have a parameter `-DockerEnterpriseEdition` anymore, so it seems like the old script is still present

**Comment by Hansdevries** [comment]
Looks great now:
Creating network "bcinab_backend" with driver "nat"
Creating network "bcinab_frontend" with driver "nat"
Creating bcinab_api_1 ... done
Creating bcinab_gui_1 ... done
Attaching to bcinab_api_1, bcinab_gui_1
api_1  | Hosting environment: Production
api_1  | Content root path: C:\app
api_1  | Now listening on: http://[::]:80
api_1  | Application started. Press Ctrl+C to shut down

**Comment by AndriusAndrulevicius** [comment]
Port 8080 as actually in use so I've removed it.
When using Start-BCinaB
PS C:\BCinaB> Start-BCinaB
Creating network "bcinab_backend" with driver "nat"
Creating network "bcinab_frontend" with driver "nat"
Creating bcinab_api_1 ... done
Creating bcinab_gui_1 ... done
Attaching to bcinab_api_1, bcinab_gui_1
api_1  |
api_1  |
api_1  | Unhandled Exception: Unhandled Exception: System.TimeoutException: The operation has timed out.
api_1  |    at System.IO.Pipes.NamedPipeClientStream.ConnectInternal(Int32 timeout, CancellationToken cancellationToken, Int32 startTime)
api_1  |    at System.IO.Pipes.NamedPipeClientStream.<>c__DisplayClass20_0.<ConnectAsync>b__0()
api_1  |    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
api_1  | --- End of stack trace from previous location where exception was thrown ---
api_1  |    at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
api_1  | --- End of stack trace from previous location where exception was thrown ---
api_1  |    at Docker.DotNet.DockerClient.<>c__DisplayClass6_0.<<-ctor>b__0>d.MoveNext()
api_1  | --- End of stack trace from previous location where exception was thrown ---
api_1  |    at Microsoft.Net.Http.Client.ManagedHandler.ProcessRequestAsync(HttpRequestMessage request, CancellationToken cancellationToken)
api_1  |    at Microsoft.Net.Http.Client.ManagedHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
api_1  |    at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
api_1  |    at Docker.DotNet.DockerClient.PrivateMakeRequestAsync(TimeSpan timeout, HttpCompletionOption completionOption, HttpMethod method, String path, IQueryString queryString, IDictionary`2 headers, IRequestContent data, CancellationToken cancellationToken)
api_1  |    at Docker.DotNet.DockerClient.MakeRequestForStreamAsync(IEnumerable`1 errorHandlers, HttpMethod method, String path, IQueryString queryString, IRequestContent body, IDictionary`2 headers, TimeSpan timeout, CancellationToken token)
api_1  |    at Docker.DotNet.Models.StreamUtil.MonitorStreamForMessagesAsync[T](Task`1 streamTask, DockerClient client, CancellationToken cancel, IProgress`1 progress)
api_1  |    at api.Services.EngineMonitorService.ListenToEngine() in C:\src\api\Services\EngineMonitorService.cs:line 54
api_1  |    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
api_1  | --- End of stack trace from previous location where exception was thrown ---
api_1  |    at System.Threading.ThreadPoolWorkQueue.Dispatch()
api_1  | System.TimeoutException: The operation has timed out.
api_1  |    at System.IO.Pipes.NamedPipeClientStream.ConnectInternal(Int32 timeout, CancellationToken cancellationToken, Int32 startTime)
api_1  |    at System.IO.Pipes.NamedPipeClientStream.<>c__DisplayClass20_0.<ConnectAsync>b__0()
api_1  |    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
api_1  | --- End of stack trace from previous location where exception was thrown ---
api_1  |    at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
api_1  | --- End of stack trace from previous location where exception was thrown ---
api_1  |    at Docker.DotNet.DockerClient.<>c__DisplayClass6_0.<<-ctor>b__0>d.MoveNext()
api_1  | --- End of stack trace from previous location where exception was thrown ---
api_1  |    at Microsoft.Net.Http.Client.ManagedHandler.ProcessRequestAsync(HttpRequestMessage request, CancellationToken cancellationToken)
api_1  |    at Microsoft.Net.Http.Client.ManagedHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
api_1  |    at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
api_1  |    at Docker.DotNet.DockerClient.PrivateMakeRequestAsync(TimeSpan timeout, HttpCompletionOption completionOption, HttpMethod method, String path, IQueryString queryString, IDictionary`2 headers, IRequestContent data, CancellationToken cancellationToken)
api_1  |    at Docker.DotNet.DockerClient.MakeRequestForStreamAsync(IEnumerable`1 errorHandlers, HttpMethod method, String path, IQueryString queryString, IRequestContent body, IDictionary`2 headers, TimeSpan timeout, CancellationToken token)
api_1  |    at Docker.DotNet.Models.StreamUtil.MonitorStreamForMessagesAsync[T](Task`1 streamTask, DockerClient client, CancellationToken cancel, IProgress`1 progress)
api_1  |    at api.Services.EngineMonitorService.ListenToEngine() in C:\src\api\Services\EngineMonitorService.cs:line 54
api_1  |    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
api_1  | --- End of stack trace from previous location where exception was thrown ---
api_1  |    at System.Threading.ThreadPoolWorkQueue.Dispatch()
bcinab_api_1 exited with code 3762504530

Despite all the errors I can access the http://localhost:8080/.
I've tried creating an OnPrem container but got the following error:
Backend returned code 504, message was: <!DOCTYPE html> <html> <head> <title>Error</title> <style> body { width: 35em; margin: 0 auto; font-family: Tahoma, Verdana, Arial, sans-serif; } </style> </head> <body> <h1>An error occurred.</h1> <p>Sorry, the page you are looking for is currently unavailable.<br/> Please try again later.</p> <p>If you are the system administrator of this resource then you should check the error log for details.</p> <p><em>Faithfully yours, nginx.</em></p> </body> </html>

**Comment by tfenster** [comment]
@Hansdevries thanks!

@AndriusAndrulevicius that looks like the frontend works, but the backend doesn't. Could you try the following:

1. Restart your PC or Server to make sure you the previous attempts didn't mess anything up
1. Download https://raw.githubusercontent.com/tfenster/BCinaB/master/stuff/BCinaB.psm1 again
1. Run import-module BCinaB.psm1
1. Run Update-BCinaB

Hopefully that should get you up and running

If that is too much effort for just trying a buggy alpha with not too much benefit, just let me know, no problem

**Comment by AndriusAndrulevicius** [comment]
Looks like restart worked.
