### ISSUE TITLE
Unable to install - authentication required

### ISSUE THREAD

**Issue by FBakkensen** [tfenster/BCinaB#20]
When i try to install, i get the following error.

`Downloading current definitions from github.com/tfenster/BCinaBCreating network "bcinab_backend" with driver "nat"`
`Creating network "bcinab_frontend" with driver "nat"`
`Pulling api (arssolvendi.azurecr.io/bcinab-api:alpha6)...`
`ERROR: Get https://arssolvendi.azurecr.io/v2/bcinab-api/manifests/alpha6: unauthorized: authentication required`

**Comment by Hansdevries** [comment]
Did you have get the credentials from tobias fenster? (did you send hem an email for futher instruction?
