### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by CBlasek** [tfenster/BCinaB#24]
Im running windows 10 - 1809, I have imported the module and when running Start-BCinaB I receive the following:

PS C:\docker\BC> Start-BCinaB
docker-compose : Creating network "bcinab_backend" with driver "nat"
At line:1 char:1
+ docker-compose -p bcinab -f c:\programdata\bcinab\docker-compose.yml  ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (Creating networ...th driver "nat":String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
plugin "nat" not found

**Comment by tfenster** [comment]
@CBlasek That looks like you are running Docker for Windows in Linux mode. Please make sure to run in Windows mode (see https://docs.docker.com/docker-for-windows/#switch-between-windows-and-linux-containers) for an explanation how to do that and verify with e.g.
```docker run mcr.microsoft.com/windows/nanoserver:1809```

**Comment by CBlasek** [comment]
You are correct. I thought I had switched it over when I went back to the stable docker build.It is working, very nicely!
