### ISSUE TITLE
Cannot set container name during creation

### ISSUE THREAD

**Issue by demiliani** [tfenster/BCinaB#4]
Can you please add the possibility to choose a container name during creation? Random names are very awful :)

**Comment by tfenster** [comment]
@demiliani Should be there in alpha4. Can you follow the instructions here https://github.com/tfenster/BCinaB/wiki#how-to-update-to-a-new-release to update and test again? 

![image](https://user-images.githubusercontent.com/15346084/50665610-9aaa7080-0fb1-11e9-8249-a4f5120f46fa.png)

**Comment by demiliani** [comment]
I’ve updated to alpha4, I can see the new details pane (enriched) but not the container name. Maybe it’s because I’ve not totally restarted (no docker-compose down). I’ll try this.

**Comment by tfenster** [comment]
@demiliani the new details pane came with alpha2. Can you check the image for your running bcinab containers? It should be arssolvendi.azurecr.io/bcinab-gui:alpha4 and bcinab-api:alpha4

**Comment by demiliani** [comment]
I’ll report the result later today. Thanks.

**Comment by demiliani** [comment]
It works now. Thanks
