### ISSUE TITLE
Confirm messages

### ISSUE THREAD

**Issue by demiliani** [tfenster/BCinaB#6]
Could be interesting to have a confirmation message for starting and (expecially!!) deleting a container.

**Comment by tfenster** [comment]
In alpha4 (see https://github.com/tfenster/BCinaB/wiki#how-to-update-to-a-new-release for instructions to upgrade) there should be a confirm dialog before deleting a container. Can you please update and test?

**Comment by demiliani** [comment]
I’ll test today, sorry for the delay but I was out. Thanks for the update.

**Comment by tfenster** [comment]
No problem, just wanted to ask

**Comment by demiliani** [comment]
It works.
